name: CI
run-name: CI | 持续集成

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main, develop, test ]
    workflow_dispatch:  # 手动触发

jobs:
    ic10-compiler-core:
        name: IC10 Compiler Core | IC10编译器核心
        strategy:
            matrix:
                include:
                    -   os: ubuntu-latest
                        script-dir: /bashShell
                        script-name: buildIC10CompilerCore.sh
                    -   os: windows-latest
                        script-dir: /powerShell
                        script-name: BuildIC10CompilerCore.ps1
        uses: ./.github/workflows/cpp-workflow.yml
        with:
            os: ${{ matrix.os }}
            script-dir: code/scripts${{ matrix.script-dir }}
            script-name: ${{ matrix.script-name }}

#    ic10-compiler-node:
#        name: IC10 Compiler Node.js Bindings | IC10编译器Node.js绑定
#        needs: ic10-compiler-core
#        strategy:
#            matrix:
#                include:
#                    -   os: ubuntu-latest
#                        script-dir: /bashShell
#                        script-name: buildIC10CompilerNode.sh
#                    -   os: windows-latest
#                        script-dir: /powerShell
#                        script-name: BuildIC10CompilerNode.ps1
#        uses: ./.github/workflows/node-workflow.yml
#        with:
#            os: ${{ matrix.os }}
#            script-dir: code/scripts${{ matrix.script-dir }}
#            script-name: ${{ matrix.script-name }}
